# Trigger the workflow on pull requests and pushes to the main branch
on:
  pull_request:
  branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: lint
      run: npm run lint
