# Trigger the workflow on pull requests and pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install npm dependencies
        run: npm ci
      - name: lint
        run: npm run lint

  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install npm dependencies
        run: npm ci
      - name: Build Docusaurus site
        run: npm run docusaurus:build
